// Filter Data Constants
// Real data provided by user for Jenis Layanan (Services)

export const SERVICE_CATEGORIES = [
  {
    id: "01.01",
    name: "Retribusi Pelayanan Kesehatan",
    value: "01.01",
    gol_id: "01",
  },
  {
    id: "01.02",
    name: "Retribusi Pelayanan Tera/Tera Ulang",
    value: "01.02",
    gol_id: "01",
  },
  {
    id: "01.03",
    name: "Retribusi Penggantian Biaya Cetak peta",
    value: "01.03",
    gol_id: "01",
  },
  {
    id: "01.04",
    name: "Retribusi Pelayanan Pendidikan",
    value: "01.04",
    gol_id: "01",
  },
  {
    id: "01.23",
    name: "Pendapatan Pelayanan Diklat",
    value: "01.23",
    gol_id: "01",
  },
  { id: "02.01", name: "Retribusi KAYADA", value: "02.01", gol_id: "02" },
  {
    id: "02.02",
    name: "Retribusi Tempat Pelelangan",
    value: "02.02",
    gol_id: "02",
  },
  {
    id: "02.03",
    name: "Retribusi Tempat Penginapan/Pesanggrahan/Villa",
    value: "02.03",
    gol_id: "02",
  },
  {
    id: "02.04",
    name: "Retribusi Penjualan Produk usaha Daerah",
    value: "02.04",
    gol_id: "02",
  },
  { id: "02.05", name: "Retribusi Terminal", value: "02.05", gol_id: "02" },
  {
    id: "02.06",
    name: "Retribusi Pelayanan Kepelabuhan",
    value: "02.06",
    gol_id: "02",
  },
  {
    id: "02.07",
    name: "Retribusi Tempat Rekreasi dan Olahraga",
    value: "02.07",
    gol_id: "02",
  },
  {
    id: "02.16",
    name: "Penyediaan tempat khusus parkir diluar badan jalan",
    value: "02.16",
    gol_id: "02",
  },
  {
    id: "02.17",
    name: "Retribusi Pemanfaatan Aset Daerah",
    value: "02.17",
    gol_id: "02",
  },
  {
    id: "02.18",
    name: "Retribusi Pelayanan Jasa Kepelabuhan",
    value: "02.18",
    gol_id: "02",
  },
  {
    id: "02.19",
    name: "Penyediaan Tempat Kegiatan Usaha",
    value: "02.19",
    gol_id: "02",
  },
  {
    id: "02.20",
    name: "Retribusi Penjualan Hasil Produksi Usaha Pemerintah Daerah",
    value: "02.20",
    gol_id: "02",
  },
  {
    id: "02.21",
    name: "Retribusi Penyediaan Tempat Kegiatan Usaha berupa Pasar, Grosir, Pertokoan, dan Tempat Kegiatan Usaha Lainnya",
    value: "02.21",
    gol_id: "02",
  },
  {
    id: "02.22",
    name: "Retribusi Pelayanan Tempat Rekreasi, Pariwisata, dan Olahraga",
    value: "02.22",
    gol_id: "02",
  },
  { id: "03.01", name: "Retribusi Izin Trayek", value: "03.01", gol_id: "03" },
  {
    id: "03.02",
    name: "Retribusi Izin Usaha Perikanan",
    value: "03.02",
    gol_id: "03",
  },
  {
    id: "03.03",
    name: "Retribusi Perpanjangan Izin Mempekerjakan Tenaga Asing",
    value: "03.03",
    gol_id: "03",
  },
  {
    id: "03.15",
    name: "Retribusi Pengelolaan Pertambangan Rakyat",
    value: "03.15",
    gol_id: "03",
  },
];

// Real data for Pengelola (Managers/OPD) - 36 items
export const DUMMY_MANAGERS = [
  { id: "01", name: "Dinas Pendidikan", value: "01" },
  { id: "02", name: "Dinas Kesehatan", value: "02" },
  { id: "03", name: "Dinas Pekerjaan Umum Dan Penataan Ruang", value: "03" },
  {
    id: "04",
    name: "Dinas Pekerjaan Umum, Sumber Daya Air Dan Penataan Ruang",
    value: "04",
  },
  { id: "05", name: "Badan Pengelola Pendapatan Daerah", value: "05" },
  { id: "06", name: "Badan Perencanaan Pembangunan Daerah", value: "06" },
  { id: "07", name: "Dinas Perhubungan", value: "07" },
  { id: "08", name: "Dinas Lingkungan Hidup Dan Kehutanan", value: "08" },
  { id: "09", name: "Dinas Sosial", value: "09" },
  { id: "10", name: "Dinas Tenagakerja Dan Transmigrasi", value: "10" },
  { id: "11", name: "Dinas Koperasi, Usaha Kecil Dan Menengah", value: "11" },
  { id: "12", name: "Dinas Kepemudaan Dan Olahraga", value: "12" },
  { id: "13", name: "Biro Umum Setda Prov. Jateng", value: "13" },
  { id: "14", name: "Sekretariat Dprd", value: "14" },
  { id: "15", name: "Badan Penghubung", value: "15" },
  {
    id: "16",
    name: "Badan Pengembangan Sumber Daya Manusia Daerah",
    value: "16",
  },
  { id: "17", name: "Dinas Kearsipan Dan Perpustakaan", value: "17" },
  { id: "18", name: "Dinas Pertanian Dan Peternakan", value: "18" },
  { id: "19", name: "Dinas Peternakan Dan Kesehatan Hewan", value: "19" },
  { id: "20", name: "Dinas Energi Dan Sumber Daya Mineral", value: "20" },
  { id: "21", name: "Dinas Kelautan Dan Perikanan", value: "21" },
  { id: "22", name: "Dinas Perindustrian Dan Perdagangan", value: "22" },
  { id: "23", name: "Badan Pengelola Keuangan Dan Aset Daerah", value: "23" },
  { id: "24", name: "Satuan Polisi Pamong Praja", value: "24" },
  {
    id: "25",
    name: "Dinas Penanaman Modal Dan Pelayanan Terpadu Satu Pintu",
    value: "25",
  },
  { id: "26", name: "Badan Kepegawaian Daerah", value: "26" },
  { id: "27", name: "Dinas Ketahanan Pangan", value: "27" },
  { id: "28", name: "Rumah Sakit Umum Daerah Dr. Moewardi", value: "28" },
  {
    id: "29",
    name: "Rumah Sakit Umum Daerah Prof. Dr. Margono Soekarjo",
    value: "29",
  },
  { id: "30", name: "Rumah Sakit Umum Daerah Dr. Adhyatma", value: "30" },
  { id: "31", name: "Rumah Sakit Umum Daerah Dr. Rehatta", value: "31" },
  {
    id: "32",
    name: "Rumah Sakit Jiwa Daerah Dr. Amino Gondohutomo",
    value: "32",
  },
  { id: "33", name: "Rumah Sakit Jiwa Daerah Dr. Arif Zainuddin", value: "33" },
  {
    id: "34",
    name: "Rumah Sakit Jiwa Daerah Dr. Rm. Soedjarwadi",
    value: "34",
  },
  { id: "35", name: "Rumah Sakit Mata Soepardjo Rustam", value: "35" },
  {
    id: "36",
    name: "Dinas Kebudayaan, Pariwisata Dan Ekonomi Kreatif",
    value: "36",
  },
];

// Lokasi (Cities) - Real data for Jawa Tengah (35 cities)
export const DUMMY_CITIES = [
  { id: "3301", name: "Kabupaten Cilacap", value: "3301" },
  { id: "3302", name: "Kabupaten Banyumas", value: "3302" },
  { id: "3303", name: "Kabupaten Purbalingga", value: "3303" },
  { id: "3304", name: "Kabupaten Banjarnegara", value: "3304" },
  { id: "3305", name: "Kabupaten Kebumen", value: "3305" },
  { id: "3306", name: "Kabupaten Purworejo", value: "3306" },
  { id: "3307", name: "Kabupaten Wonosobo", value: "3307" },
  { id: "3308", name: "Kabupaten Magelang", value: "3308" },
  { id: "3309", name: "Kabupaten Boyolali", value: "3309" },
  { id: "3310", name: "Kabupaten Klaten", value: "3310" },
  { id: "3311", name: "Kabupaten Sukoharjo", value: "3311" },
  { id: "3312", name: "Kabupaten Wonogiri", value: "3312" },
  { id: "3313", name: "Kabupaten Karanganyar", value: "3313" },
  { id: "3314", name: "Kabupaten Sragen", value: "3314" },
  { id: "3315", name: "Kabupaten Grobogan", value: "3315" },
  { id: "3316", name: "Kabupaten Blora", value: "3316" },
  { id: "3317", name: "Kabupaten Rembang", value: "3317" },
  { id: "3318", name: "Kabupaten Pati", value: "3318" },
  { id: "3319", name: "Kabupaten Kudus", value: "3319" },
  { id: "3320", name: "Kabupaten Jepara", value: "3320" },
  { id: "3321", name: "Kabupaten Demak", value: "3321" },
  { id: "3322", name: "Kabupaten Semarang", value: "3322" },
  { id: "3323", name: "Kabupaten Temanggung", value: "3323" },
  { id: "3324", name: "Kabupaten Kendal", value: "3324" },
  { id: "3325", name: "Kabupaten Batang", value: "3325" },
  { id: "3326", name: "Kabupaten Pekalongan", value: "3326" },
  { id: "3327", name: "Kabupaten Pemalang", value: "3327" },
  { id: "3328", name: "Kabupaten Tegal", value: "3328" },
  { id: "3329", name: "Kabupaten Brebes", value: "3329" },
  { id: "3371", name: "Kota Magelang", value: "3371" },
  { id: "3372", name: "Kota Surakarta", value: "3372" },
  { id: "3373", name: "Kota Salatiga", value: "3373" },
  { id: "3374", name: "Kota Semarang", value: "3374" },
  { id: "3375", name: "Kota Pekalongan", value: "3375" },
  { id: "3376", name: "Kota Tegal", value: "3376" },
];

export const DEFAULT_FILTERS = {
  city: "",
  manager: "",
  serviceType: "",
  search: "",
};

export const EMPTY_OPTIONS = {
  cities: DUMMY_CITIES,
  managers: DUMMY_MANAGERS,
  services: SERVICE_CATEGORIES,
};
